
/**********************************************************
 * AlertaEF.java
 * Alertas de segurança enviados pelo usuário
 * Version: 1.0.1
 * Generated by Easyfire. Do not modify this code 
 **********************************************************/

package br.com.easyhome.easyfire.models;

import br.com.easyhome.easyfire.models.AlertaEF;
import br.com.easyhome.easyfire.service.AlertaServiceEF;
import br.com.easyhome.easyfire.models.MembroEF;
import br.com.easyhome.easyfire.service.MembroServiceEF;
import br.com.easyhome.easyfire.models.MembroEF;
import br.com.easyhome.easyfire.service.MembroServiceEF;
import br.com.easyhome.easyfire.models.GrupoEF;
import br.com.easyhome.easyfire.service.GrupoServiceEF;


import com.google.firebase.database.Exclude;
import com.google.firebase.database.IgnoreExtraProperties;
import android.databinding.BaseObservable;
import android.support.annotation.NonNull;

@IgnoreExtraProperties
public class AlertaEF implements Comparable<AlertaEF>{

  //Firebase attributes
  @Exclude
  private String key;
  
  @Exclude
  private Class[] parents;
  
  @Exclude
  private String[] parentKeys;


  
  //Title of the chat room
  private String title = "";
  
  //Last message in this thread
  private String lastMessage = "";
  
  //Momento que o alerta foi gerado
  private Long timestamp = 0L;
  
  //Foto do grupo
  private String avatar = "";
  
  //Descrição do alerta
  private String descricao = "";
  
  //Descricao
  private String nome = "";
  
  
  
  @Exclude private AlertaEF alertaEF = null;
  
  
  
  @Exclude private MembroEF membrosEF = null;
  
  //Foto do avatar do membro
  private String avatarMemebro = "";
  
  //Foto associada ao alerta
  private String foto = "";
  
  //Nome do arquivo no dispositivo
  
  @Exclude private String fotoLocal = "";
  
  //Local onde o alerta foi gerado
  private String localizacao = "";
  
  //Nome do membro que gerou o Alerta
  private String nomeMembro = "";
  
  //Nome do membro que gerou o ultimo comentário
  private String nomeMembroUltimoComentario = "";
  
  //Número de comentários do alerta
  private Long numeroComentarios = 0L;
  
  //Flag que indica que o thumbnail da foto ja foi carregado para resolução 1x
  private Boolean ta1x = false;
  
  //Flag que indica que o thumbnail  da foto ja foi carregado para resolução 2x
  private Boolean ta2x = false;
  
  //Flag que indica que o thumbnail da foto ja foi carregado para resolução 3x
  private Boolean ta3x = false;
  
  //Tipo do alerta
  private String tipo = "";
  
  
  private String membroEFPath = "";
  
  
  
  @Exclude private MembroEF membroEF = null;
  
  
  private String grupoEFPath = "";
  
  
  
  @Exclude private GrupoEF grupoEF = null;
  

  //Construtores
  public AlertaEF(){}
  
  public AlertaEF(String key){
    this.key = key;
  }
  
  //Getters e Setters
  
  @Exclude
  public String getKey(){
    return this.key;
  }
  
  @Exclude
  public void setKey(String key){
    this.key = key;
  }
  
  @Exclude
  public Class[] getParents(){
    return this.parents;
  }
  
  @Exclude
  public void setParents(Class[] parents){
    this.parents = parents;
  }
  
  @Exclude
  public String[] getParentKeys(){
    return this.parentKeys;
  }
  
  @Exclude
  public void setParentKeys(String[] parentKeys){
    this.parentKeys = parentKeys;
  }
  
  
  
  
  public String getTitle(){
    
   return this.title;
   
  }

  public void setTitle(String title){
   this.title = title;
   
  } 

  
  
  public String getLastMessage(){
    
   return this.lastMessage;
   
  }

  public void setLastMessage(String lastMessage){
   this.lastMessage = lastMessage;
   
  } 

  
  
  public Long getTimestamp(){
    
   return this.timestamp;
   
  }

  public void setTimestamp(Long timestamp){
   this.timestamp = timestamp;
   
  } 

  
  
  public String getAvatar(){
    
   return this.avatar;
   
  }

  public void setAvatar(String avatar){
   this.avatar = avatar;
   
  } 

  
  
  public String getDescricao(){
    
   return this.descricao;
   
  }

  public void setDescricao(String descricao){
   this.descricao = descricao;
   
  } 

  
  
  public String getNome(){
    
   return this.nome;
   
  }

  public void setNome(String nome){
   this.nome = nome;
   
  } 

  
  @Exclude
  public AlertaEF getAlertaEF(){
    
   if (this.alertaEF == null){
     this.alertaEF = AlertaServiceEF.load(this.alertaEFPath,this.alertaEF.getClass());
   }
   return this.alertaEF;
   
  }

  public void setAlertaEF(AlertaEF alertaEF){
   this.alertaEF = alertaEF;
   
  } 

  
  @Exclude
  public MembroEF getMembrosEF(){
    
   if (this.membrosEF == null){
     this.membrosEF = MembrosServiceEF.load(this.membrosEFPath,this.membrosEF.getClass());
   }
   return this.membrosEF;
   
  }

  public void setMembrosEF(MembroEF membrosEF){
   this.membrosEF = membrosEF;
   
  } 

  
  
  public String getAvatarMemebro(){
    
   return this.avatarMemebro;
   
  }

  public void setAvatarMemebro(String avatarMemebro){
   this.avatarMemebro = avatarMemebro;
   
  } 

  
  
  public String getFoto(){
    
   return this.foto;
   
  }

  public void setFoto(String foto){
   this.foto = foto;
   
  } 

  
  @Exclude
  public String getFotoLocal(){
    
   return this.fotoLocal;
   
  }

  public void setFotoLocal(String fotoLocal){
   this.fotoLocal = fotoLocal;
   
  } 

  
  
  public String getLocalizacao(){
    
   return this.localizacao;
   
  }

  public void setLocalizacao(String localizacao){
   this.localizacao = localizacao;
   
  } 

  
  
  public String getNomeMembro(){
    
   return this.nomeMembro;
   
  }

  public void setNomeMembro(String nomeMembro){
   this.nomeMembro = nomeMembro;
   
  } 

  
  
  public String getNomeMembroUltimoComentario(){
    
   return this.nomeMembroUltimoComentario;
   
  }

  public void setNomeMembroUltimoComentario(String nomeMembroUltimoComentario){
   this.nomeMembroUltimoComentario = nomeMembroUltimoComentario;
   
  } 

  
  
  public Long getNumeroComentarios(){
    
   return this.numeroComentarios;
   
  }

  public void setNumeroComentarios(Long numeroComentarios){
   this.numeroComentarios = numeroComentarios;
   
  } 

  
  
  public Boolean getTa1x(){
    
   return this.ta1x;
   
  }

  public void setTa1x(Boolean ta1x){
   this.ta1x = ta1x;
   
  } 

  
  
  public Boolean getTa2x(){
    
   return this.ta2x;
   
  }

  public void setTa2x(Boolean ta2x){
   this.ta2x = ta2x;
   
  } 

  
  
  public Boolean getTa3x(){
    
   return this.ta3x;
   
  }

  public void setTa3x(Boolean ta3x){
   this.ta3x = ta3x;
   
  } 

  
  
  public String getTipo(){
    
   return this.tipo;
   
  }

  public void setTipo(String tipo){
   this.tipo = tipo;
   
  } 

  
  
  public String getMembroEFPath(){
    
   return this.membroEFPath;
   
  }

  public void setMembroEFPath(String membroEFPath){
   this.membroEFPath = membroEFPath;
   
  } 

  
  @Exclude
  public MembroEF getMembroEF(){
    
   if (this.membroEF == null){
     this.membroEF = MembroServiceEF.load(this.membroEFPath,this.membroEF.getClass());
   }
   return this.membroEF;
   
  }

  public void setMembroEF(MembroEF membroEF){
   this.membroEF = membroEF;
   
  } 

  
  
  public String getGrupoEFPath(){
    
   return this.grupoEFPath;
   
  }

  public void setGrupoEFPath(String grupoEFPath){
   this.grupoEFPath = grupoEFPath;
   
        this.getGrupoEFPath();
   
  } 

  
  @Exclude
  public GrupoEF getGrupoEF(){
    
   return this.grupoEF;
   
  }

  public void setGrupoEF(GrupoEF grupoEF){
   this.grupoEF = grupoEF;
   
  } 

  	

  @Override
  public String toString() {
    return "Alerta{" +
     "key='" + key + '\'' +
     ", title='" + title + '\'' +
     ", lastMessage='" + lastMessage + '\'' +
     ", timestamp='" + timestamp + '\'' +
     ", avatar='" + avatar + '\'' +
     ", descricao='" + descricao + '\'' +
     ", nome='" + nome + '\'' +
     ", alertaEF='" + alertaEF + '\'' +
     ", membrosEF='" + membrosEF + '\'' +
     ", avatarMemebro='" + avatarMemebro + '\'' +
     ", foto='" + foto + '\'' +
     ", fotoLocal='" + fotoLocal + '\'' +
     ", localizacao='" + localizacao + '\'' +
     ", nomeMembro='" + nomeMembro + '\'' +
     ", nomeMembroUltimoComentario='" + nomeMembroUltimoComentario + '\'' +
     ", numeroComentarios='" + numeroComentarios + '\'' +
     ", ta1x='" + ta1x + '\'' +
     ", ta2x='" + ta2x + '\'' +
     ", ta3x='" + ta3x + '\'' +
     ", tipo='" + tipo + '\'' +
     ", membroEFPath='" + membroEFPath + '\'' +
     ", membroEF='" + membroEF + '\'' +
     ", grupoEFPath='" + grupoEFPath + '\'' +
     ", grupoEF='" + grupoEF + '\'' +
     "}";
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
        
    AlertaEF alertaEF = (AlertaEF ) o;
        
    return key != null ? key.equals(alertaEF.key) : alertaEF.key == null;

  }
  
  public boolean equalsContent(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;
      if (!super.equals(o)) return false;

      AlertaEF alertaEF = (AlertaEF ) o;
      
      
      if (title != null ? !title.equals(alertaEF.title) : alertaEF.title != null) {
        return false;
      }
      
      if (lastMessage != null ? !lastMessage.equals(alertaEF.lastMessage) : alertaEF.lastMessage != null) {
        return false;
      }
      
      if (timestamp != null ? !timestamp.equals(alertaEF.timestamp) : alertaEF.timestamp != null) {
        return false;
      }
      
      if (avatar != null ? !avatar.equals(alertaEF.avatar) : alertaEF.avatar != null) {
        return false;
      }
      
      if (descricao != null ? !descricao.equals(alertaEF.descricao) : alertaEF.descricao != null) {
        return false;
      }
      
      if (nome != null ? !nome.equals(alertaEF.nome) : alertaEF.nome != null) {
        return false;
      }
      
      if (alertaEF != null ? !alertaEF.equals(alertaEF.alertaEF) : alertaEF.alertaEF != null) {
        return false;
      }
      
      if (membrosEF != null ? !membrosEF.equals(alertaEF.membrosEF) : alertaEF.membrosEF != null) {
        return false;
      }
      
      if (avatarMemebro != null ? !avatarMemebro.equals(alertaEF.avatarMemebro) : alertaEF.avatarMemebro != null) {
        return false;
      }
      
      if (foto != null ? !foto.equals(alertaEF.foto) : alertaEF.foto != null) {
        return false;
      }
      
      if (fotoLocal != null ? !fotoLocal.equals(alertaEF.fotoLocal) : alertaEF.fotoLocal != null) {
        return false;
      }
      
      if (localizacao != null ? !localizacao.equals(alertaEF.localizacao) : alertaEF.localizacao != null) {
        return false;
      }
      
      if (nomeMembro != null ? !nomeMembro.equals(alertaEF.nomeMembro) : alertaEF.nomeMembro != null) {
        return false;
      }
      
      if (nomeMembroUltimoComentario != null ? !nomeMembroUltimoComentario.equals(alertaEF.nomeMembroUltimoComentario) : alertaEF.nomeMembroUltimoComentario != null) {
        return false;
      }
      
      if (numeroComentarios != null ? !numeroComentarios.equals(alertaEF.numeroComentarios) : alertaEF.numeroComentarios != null) {
        return false;
      }
      
      if (ta1x != null ? !ta1x.equals(alertaEF.ta1x) : alertaEF.ta1x != null) {
        return false;
      }
      
      if (ta2x != null ? !ta2x.equals(alertaEF.ta2x) : alertaEF.ta2x != null) {
        return false;
      }
      
      if (ta3x != null ? !ta3x.equals(alertaEF.ta3x) : alertaEF.ta3x != null) {
        return false;
      }
      
      if (tipo != null ? !tipo.equals(alertaEF.tipo) : alertaEF.tipo != null) {
        return false;
      }
      
      if (membroEFPath != null ? !membroEFPath.equals(alertaEF.membroEFPath) : alertaEF.membroEFPath != null) {
        return false;
      }
      
      if (membroEF != null ? !membroEF.equals(alertaEF.membroEF) : alertaEF.membroEF != null) {
        return false;
      }
      
      if (grupoEFPath != null ? !grupoEFPath.equals(alertaEF.grupoEFPath) : alertaEF.grupoEFPath != null) {
        return false;
      }
      
      if (grupoEF != null ? !grupoEF.equals(alertaEF.grupoEF) : alertaEF.grupoEF != null) {
        return false;
      }
      
          
      return true;

  }
  
  @Override
  public int hashCode() {
    return key != null ? key.hashCode() : 0;
  }
  
  
  public boolean isChild(){
    return parents != null;
  }
  
  @Override
  public int compareTo(@NonNull AlertaEF alertaEF) {
      return this.key.compareTo(alertaEF.getKey());
  }
  
  
  
}
